# Generated by cucumber-sinatra. (2013-02-14 23:09:45 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/robin.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Robin

class RobinWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RobinWorld.new
end
